# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\temp\pkg\nilm_metadata, last modified Sun Jun 24 19:00:51 2018
# ------------------------------------------------

package:
    name: nilm_metadata
    version: 0.2.3.dev
source:
    git_url: https://github.com/nilmtk/nilm_metadata.git
build:
    string: '0'
    noarch: python
requirements:
    host:
        - python 
        - setuptools
    run:
        - PyYAML
        - pandas
        - six
extra:
    copy_test_source_files: true
    final: true
