package:
    name: nilm_metadata
    version: 0.2.4
source:
    path: ..
build:
    noarch: python
    
requirements:
    host:
        - python 
        - setuptools
    run:
        - PyYAML
        - pandas
        - six
extra:
    copy_test_source_files: true
    final: true
